#pragma once

#include "BuildVer.h"
#define TOSTRING2(arg) #arg
#define TOSTRING(arg) TOSTRING2(arg)
#define BML_VERSION TOSTRING(BML_MAJOR_VER) "." TOSTRING(BML_MINOR_VER) "." TOSTRING(BML_BUILD_VER)
#define BML_RC_VERSION TOSTRING(BML_MAJOR_VER) "." TOSTRING(BML_MINOR_VER) ".0." TOSTRING(BML_BUILD_VER)
